start: (text | template)+

template: "{{" WS_IL? function_call WS_IL? "}}"

function_call: function_name function_arg?

function_arg: "(" args* argument? ")"

args: argument ","

function_name: /[A-Za-z0-9_]+/

argument: argument_name WS_IL? "=" WS_IL? argument_value

argument_value: /[A-Za-z0-9_\-. äöüÄÖÜß]+/

argument_name: /[A-Za-z0-9_]+/

text: /[^{}]+/

WS_IL: /\s+/

%import common.WS_INLINE
%ignore WS_IL