start: (text | template)+

template: "{{" WS_INLINE* function_call WS_INLINE* "}}"

function_call: function_name function_arg?

function_arg: "(" args* argument? ")"

args: argument ","

function_name: /[A-Za-z0-9_]+/

argument: argument_name WS_INLINE* "=" WS_INLINE* argument_value

argument_value: /[A-Za-z0-9_\-. äöüÄÖÜß]+/

argument_name: /[A-Za-z0-9_]+/

text: /[^{}]+/

%import common.WS_INLINE
%ignore WS_INLINE