FB_ARBEITSWELT = "Arbeitswelt"
FB_BIOLOGIE = "Biologie"
FB_CHEMIE = "Chemie"
FB_GEO = "Geo- und Raumwissenschaften"
FB_MATHE_INFO = "Mathematik/Informatik"
FB_PHYSIK = "Physik"
FB_TECHNIK = "Technik"

SPARTE_JUNIOR = "JR"
SPARTE_JUFO = "JF"

FACHBEREICHE = [
    FB_ARBEITSWELT, FB_BIOLOGIE, FB_CHEMIE, FB_GEO, FB_MATHE_INFO, FB_PHYSIK, FB_TECHNIK
]
SPARTEN = [SPARTE_JUFO, SPARTE_JUNIOR]
